### ISSUE TITLE
Name "AppImageKit"

### ISSUE THREAD

**Issue by probonopd** [phil-harmoniq/NET_Pkg#7]
Hi, thanks for this interesting project, looks very promising. Please be aware that the name is "AppImageKit" for the project and `appimagetool` for one of the tools contained therein. Currently you write "AppImageToolkit" in the README.md and on the GitHub Releases page; such a thing does not exist.

Keep up the good work; looking forward to a "hello world" example and eventually to an example that shows how to bundle MonoDevelop as an AppImage.

**Comment by probonopd** [comment]
Thanks!

**Comment by phil-harmoniq** [comment]
Sorry about that! I just updated the project with the correct name! Thanks for making a really useful tool, I'm just a student, but working on this has really helped me learn a lot. I hope to get a guide on how everything works up soon.

**Comment by probonopd** [comment]
I had tried to bundle Mono applications but had given up at some point because I have no .net or Mono knowledge... so glad you are doing this!

**Comment by probonopd** [comment]
Ping... any chance to bundle MonoDevelop?
